### ISSUE TITLE
Refactor database suitable structure

### ISSUE THREAD

**Issue by lcaohoanq** [SWP391-613/Koi-Auction-BE#10]

**Comment by lcaohoanq** [comment]
@DuongNManh @dduongCongSon, db diagram are discussing at : https://drive.google.com/file/d/1yJ1fCAejudfIbiqd1NJNzxh_r5w5xHhB/view?usp=drive_link

**Comment by DuongNManh** [comment]
added bid_list table.
![image](https://github.com/user-attachments/assets/0cdbc686-4c2c-4372-964a-c8e361ab9fae)
